
export const FETCH_MIRROR_TEXT = "FETCH_MIRROR_TEXT";
export const FETCH_MIRROR_TEXT_REQUEST = "FETCH_MIRROR_TEXT_REQUEST";
export const FETCH_MIRROR_TEXT_SUCCESS = "FETCH_MIRROR_TEXT_SUCCESS";
export const FETCH_MIRROR_TEXT_FAILURE = "FETCH_MIRROR_TEXT_FAILURE";
